export function getName() {
    const arr = [
        "赵",
        "钱",
        "孙",
        "周",
        "吴",
        "郑",
        "王",
        "冯",
        "陈",
        "褚",
        "卫",
        "蒋",
        "沈",
        "韩",
        "杨",
        "朱",
        "秦",
        "尤",
        "许",
        "何",
        "吕",
        "施",
        "张",
        "孔",
        "曹",
        "严",
        "华",
        "金",
        "魏",
        "陶",
        "姜",
        "谢",
        "邹",
        "喻",
        "柏",
        "水",
        "窦",
        "章",
        "云",
        "苏",
        "潘",
        "葛",
        "奚",
        "范",
        "彭",
        "郎",
        "鲁",
        "韦",
        "昌",
        "马",
        "苗",
        "凤",
        "花",
        "方",
        "俞",
        "任",
        "袁",
        "柳",
        "酆",
        "鲍",
        "史",
        "唐",
    ];
    const index1 = Math.ceil(Math.random() * 100);
    const name1 = arr[index1]
        ? arr[index1]
        : arr[Math.ceil(arr.length / index1)];
    const index2 = Math.ceil(Math.random() * 100);
    const name2 = arr[index2]
        ? arr[index2]
        : arr[Math.ceil(arr.length / index2)];
    return name1 + name2;
}
